# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DypIlrWy4KaAy6QEWR4TGoy9a401M-ZP
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/userpayment.xlsx")

df

df['Upayment'] = df['Upayment'].replace('bank_debit_cards', 'DB_card')

df

df['Upayment'] = df['Upayment'].replace('bMasterCard-Eurocard', 'MS_card')

df['Upayment'] = df['Upayment'].replace('MasterCard-Eurocard', 'MS_card')

df['Upayment'] = df['Upayment'].replace('American_Express', 'AEX_card')

df['Upayment'] = df['Upayment'].replace('VISA', 'VISA_card')

df

df['Upayment'] = df['Upayment'].replace('cash', 'CASH')

df = df.rename(columns={"Upayment":"PAY _method"})

df

df.to_excel('/content/drive/MyDrive/PAYMENT.xlsx', index=False)

df.to_json('/content/drive/MyDrive/paym.json', orient='records', lines=True)

df = pd.read_excel("/content/drive/MyDrive/PAYMENT.xlsx")

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_excel("/content/drive/MyDrive/PAYMENT.xlsx")

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/PAYMENT.xlsx")

df.to_json('/content/drive/MyDrive/PAYM.json', orient='records', lines=True)

df = pd.read_json("/content/drive/MyDrive/Colab Notebooks/Working_Hours.json")

df = pd.read_json("/content/drive/MyDrive/Colab Notebooks/Working_Hours.json")

df = pd.read_json("/content/drive/MyDrive/Colab Notebooks/Working_Hours.json", strict=False)

df = pd.read_json("/content/drive/MyDrive/Colab Notebooks/Working_Hours.json")

data = pd.read_json("/content/drive/MyDrive/Colab Notebooks/Working_Hours.json", lines=True)

data

data=data.fillna(0)

data

for index, row in data.iterrows():data.at[index, 'storeId'] = 'S' + str(1000 + index)

data

data_result.to_json('/content/drive/MyDrive/working_Hours.json', orient='records', lines=True)

data.to_json('/content/drive/MyDrive/working_Hours.json', orient='records', lines=True)

df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/PAYMENT.xlsx")

df

for index, row in df.iterrows():df.at[index, 'UserId'] =str(index)

df

df.drop(columns = "nUserId")

df=df.drop(columns = "UserId")

df

for index, row in df.iterrows():df.at[index, 'userID'] =str(index)

df

for index, row in df.iterrows():df.at[index, 'userID'] =str(1+index)

for index, row in df.iterrows():df.at[index, 'userID'] =1+index

df

df.to_json('/content/drive/MyDrive/payment.json', orient='records', lines=True)

